### ISSUE TITLE
Cannot set visible signature correctly

### ISSUE THREAD

**Issue by bgn2015** [zylklab/sinaduraDesktop#30]
Hello,

I encounter the following problem to pdf documents when the pages are not in vertical A4 format: the positioning of the visual signature is not done correctly

**Comment by CesarCapillas** [comment]
Yes, the previewer is designed for A4 documents (in portrait mode).
As a walkaround, you may try to sign in the left upper corner. 

Regards.
--C.

**Comment by guszylk** [comment]
I think is possible to create a signature profile manually. The profiles are stored in .sinadura/preferences/pdf-profiles.csv the header of the file is
name,properties.ask,visible,stamp.ask,stamp.enable,stamp.path,stamp.width,stamp.height,stamp.x,stamp.y,page,certified,acrofield,reason,location

You can add new line and use the stamp.x,stamp.y with negative values to set the stamp where you want
